app:
  name: pos_main_api

#Database
spring:
  datasource:
    main:
      url: jdbc:mysql://tramway.proxy.rlwy.net:44894/pos_main_db?allowPublicKeyRetrieval=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: OsyxbUBBlTAMIogZNfYpoYrCOAMUUmyV

#    mirror:
#      url: jdbc:mysql://shuttle.proxy.rlwy.net:36085/pos_mirror_db?allowPublicKeyRetrieval=true&useSSL=false
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: OsyxbUBBlTAMIogZNfYpoYrCOAMUUmyV

    hikari:
      connection-timeout: 120000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 2
      maximum-pool-size: 4

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          packagesToScan: com.pos_main
        show-sql: true
        open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  main: 
    allow-circular-references: true

entitymanager:
  packagesToScan: com.pos_main

#File upload location in C drive    
#fileupload:
#  url: /pos-main/
#  path: 

#file:
#  upload.location: /Uploads

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    #    eureka-service-url-poll-interval-seconds: 0
#    serviceUrl:
#      defaultZone: http://localhost:7000/eureka/

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 160000000
#        readTimeout: 160000000
